on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: '0 1 * * *'
name: Build and publish to DockerHub
env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
  QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
  QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
jobs:
  stable:
    name: stable
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@main
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - 
        name: Build and Publish images
        run: |
          sudo apt-get install -y pcregrep
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          ./scripts/update-stable.sh
          export DOCKER_BUILD_CONTEXT="stable"
          export DOCKER_IMAGE_VERSION=`sed -ne "s/^ARG VERSION=['\"]\([^'\"]*\)['\"]/\1/p" stable/Dockerfile`
          export DOCKER_TAGS="stable,latest,${DOCKER_IMAGE_VERSION}"
          ./scripts/publish.sh
          git push

  alpha:
    name: alpha
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@main
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and Publish images
        run: |
          sudo apt-get install -y pcregrep
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          ./scripts/update-alpha.sh
          export DOCKER_BUILD_CONTEXT="alpha"
          export DOCKER_IMAGE_VERSION=`sed -ne "s/^ARG VERSION=['\"]\([^'\"]*\)['\"]/\1/p" alpha/Dockerfile`
          export DOCKER_TAGS="edge,alpha,${DOCKER_IMAGE_VERSION}"
          ./scripts/publish.sh
          git push

