on: [push]
name: Build and deploy on push
jobs:
  dockerhub_publish_stable:
    name: DockerHub Build and Publish stable
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Build and Publish stable to DockerHub
      uses: westonsteimel/action-docker-publish@main
      with:
        registry: 'docker.io'
        password: ${{ secrets.DOCKER_PASSWORD }}
        username: ${{ secrets.DOCKER_USERNAME }}
        image_name: 'tor-browser'
        build_context: 'stable'
        dockerfile_path: 'stable/Dockerfile'
        static_tags: 'stable'
        tag_ref: false
        tag_latest: true
        tag_version: true
        tag_sha: false
        tag_timestamp: false
  dockerhub_publish_alpha:
    name: DockerHub Build and Publish alpha
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Build and Publish alpha to DockerHub
      uses: westonsteimel/action-docker-publish@main
      with:
        registry: 'docker.io'
        password: ${{ secrets.DOCKER_PASSWORD }}
        username: ${{ secrets.DOCKER_USERNAME }}
        image_name: 'tor-browser'
        build_context: 'alpha'
        dockerfile_path: 'alpha/Dockerfile'
        static_tags: 'alpha'
        tag_ref: false
        tag_latest: false
        tag_version: true
        tag_sha: false
        tag_timestamp: false

